import { useQuery } from "@tanstack/react-query";
import { useParams } from "wouter";
import { FileText, Building, User, Calendar } from "lucide-react";
import { format } from "date-fns";

export default function SharePage() {
  const { id } = useParams();
  
  const { data: document, isLoading, error } = useQuery<any>({
    queryKey: [`/api/documents/${id}`],
    enabled: !!id
  });

  if (isLoading) return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center">
      <div className="animate-pulse text-slate-400 font-bold">Loading shareable draft...</div>
    </div>
  );

  if (error || !document) return (
    <div className="min-h-screen bg-slate-50 flex items-center justify-center">
      <div className="text-slate-400 font-bold">This share link is invalid or has expired.</div>
    </div>
  );

  return (
    <div className="min-h-screen bg-[#fdfaf6] p-4 md:p-12">
      <div className="max-w-4xl mx-auto bg-white rounded-[2rem] shadow-xl overflow-hidden border border-slate-100">
        <div className="bg-indigo-900 p-8 text-white flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div>
            <div className="inline-flex items-center gap-2 px-3 py-1 bg-white/10 rounded-full text-xs font-bold uppercase tracking-wider mb-3">
              <FileText className="w-3 h-3" /> Shared {document.type === 'cv' ? 'CV' : 'Cover Letter'}
            </div>
            <h1 className="text-3xl font-bold">{document.name}</h1>
          </div>
          <div className="flex items-center gap-3 text-indigo-200 text-sm font-medium">
            <Calendar className="w-4 h-4" />
            Created {format(new Date(document.createdAt), 'MMMM d, yyyy')}
          </div>
        </div>

        <div className="p-8 md:p-12">
          <div className="prose prose-slate max-w-none">
            <pre className="whitespace-pre-wrap font-serif text-lg leading-relaxed text-slate-800 bg-transparent border-none p-0 focus:outline-none">
              {document.content}
            </pre>
          </div>
        </div>

        <div className="p-8 bg-slate-50 border-t border-slate-100 text-center">
          <p className="text-slate-400 text-sm">
            This is a read-only preview generated by <span className="font-bold text-primary">Career Companion</span>.
          </p>
        </div>
      </div>
    </div>
  );
}
